/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.JFrame;

/**
 *
 * @author PC MC
 */
public class Authentification extends javax.swing.JFrame {

    int X,Y;
    public Authentification() {
        initComponents();
        addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                //To change body of generated methods, choose Tools | Templates.
                X = e.getX();
                Y = e.getY();
            }

        });
        addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseDragged(MouseEvent e) {
                //To change body of generated methods, choose Tools | Templates.
                int depX = e.getX() - X;
                int depY = e.getY() - Y;
                setLocation(getX()+depX,getY()+depY);

            }

        });
        setLocationRelativeTo(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panQuitterAuth = new javax.swing.JPanel();
        lQuitterAuth = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        liconeOphta2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        liconeSec2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panQuitterAuth.setBackground(new java.awt.Color(0, 102, 153));
        panQuitterAuth.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lQuitterAuth.setIcon(new javax.swing.ImageIcon(getClass().getResource("/show/ihm/x.png"))); // NOI18N
        lQuitterAuth.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lQuitterAuthMouseMoved(evt);
            }
        });
        lQuitterAuth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lQuitterAuthMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lQuitterAuthMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lQuitterAuthMousePressed(evt);
            }
        });
        panQuitterAuth.add(lQuitterAuth, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 20, 30));

        jPanel1.add(panQuitterAuth, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 40, 110));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/show/ihm/logonegh_1.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 70));

        jPanel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel4MouseMoved(evt);
            }
        });
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 30, 10));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 80));

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        liconeOphta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/show/ihm/ophtalmologue.png"))); // NOI18N
        liconeOphta2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                liconeOphta2MouseMoved(evt);
            }
        });
        liconeOphta2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                liconeOphta2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                liconeOphta2MouseExited(evt);
            }
        });
        jPanel3.add(liconeOphta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 250, 330));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        liconeSec2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/show/ihm/secretaire.PNG"))); // NOI18N
        liconeSec2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                liconeSec2MouseMoved(evt);
            }
        });
        liconeSec2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                liconeSec2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                liconeSec2MouseExited(evt);
            }
        });
        jPanel5.add(liconeSec2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 230, 290));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 750, 380));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 770, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 771, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lQuitterAuthMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lQuitterAuthMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lQuitterAuthMousePressed

    private void lQuitterAuthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lQuitterAuthMouseClicked
System.exit(0);    }//GEN-LAST:event_lQuitterAuthMouseClicked

    private void lQuitterAuthMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lQuitterAuthMouseMoved
       setCursor(HAND_CURSOR); 
    }//GEN-LAST:event_lQuitterAuthMouseMoved

    private void lQuitterAuthMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lQuitterAuthMouseExited
        setCursor(DEFAULT_CURSOR);
    }//GEN-LAST:event_lQuitterAuthMouseExited

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jPanel4MouseClicked

    private void liconeSec2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_liconeSec2MouseExited
        setCursor(DEFAULT_CURSOR);
    }//GEN-LAST:event_liconeSec2MouseExited

    private void liconeSec2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_liconeSec2MouseClicked
        new Authentifier_Secr().setVisible(true);
        dispose();
    }//GEN-LAST:event_liconeSec2MouseClicked

    private void liconeSec2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_liconeSec2MouseMoved
        setCursor(HAND_CURSOR);
    }//GEN-LAST:event_liconeSec2MouseMoved

    private void liconeOphta2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_liconeOphta2MouseExited
        setCursor(DEFAULT_CURSOR);
    }//GEN-LAST:event_liconeOphta2MouseExited

    private void liconeOphta2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_liconeOphta2MouseClicked
        new Authentifier_Ophtalmo().setVisible(true);
        dispose();
    }//GEN-LAST:event_liconeOphta2MouseClicked

    private void liconeOphta2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_liconeOphta2MouseMoved
        setCursor(HAND_CURSOR);
    }//GEN-LAST:event_liconeOphta2MouseMoved

    private void jPanel4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseMoved
      setCursor(HAND_CURSOR);
    }//GEN-LAST:event_jPanel4MouseMoved

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
         setCursor(DEFAULT_CURSOR);
    }//GEN-LAST:event_jPanel4MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Authentification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lQuitterAuth;
    private javax.swing.JLabel liconeOphta2;
    private javax.swing.JLabel liconeSec2;
    private javax.swing.JPanel panQuitterAuth;
    // End of variables declaration//GEN-END:variables
}
