/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class Fiche_Medicale extends javax.swing.JFrame {

    int X, Y;

    public Fiche_Medicale() {
        initComponents();
        addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                //To change body of generated methods, choose Tools | Templates.
                X = e.getX();
                Y = e.getY();
            }

        });
        addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseDragged(MouseEvent e) {
                //To change body of generated methods, choose Tools | Templates.
                int depX = e.getX() - X;
                int depY = e.getY() - Y;
                setLocation(getX()+depX,getY()+depY);

            }

        });

        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panQuitterFicheMed = new javax.swing.JPanel();
        lQuitterFicheMed = new javax.swing.JLabel();
        panSuperieurFicheMed = new javax.swing.JPanel();
        lReduireFichePerso = new javax.swing.JLabel();
        lSuperieurFicheMed = new javax.swing.JLabel();
        panFicheMed = new javax.swing.JPanel();
        panAnt = new javax.swing.JPanel();
        lDoc = new javax.swing.JLabel();
        tfDoc = new javax.swing.JTextField();
        lAntGeneraux = new javax.swing.JLabel();
        lAntFamiliaux = new javax.swing.JLabel();
        lAntOphtalmo = new javax.swing.JLabel();
        tfAntFamiliaux = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        tfAntOphtalmo = new javax.swing.JTextField();
        lAntecedent = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        tfAntGeneraux = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        bimporter = new javax.swing.JButton();
        panBoutonFicheMed = new javax.swing.JPanel();
        bValiderFicheMed = new javax.swing.JButton();
        panCentreFicheMed = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lTypeConsult = new javax.swing.JLabel();
        comboTypeConsult = new javax.swing.JComboBox<>();
        lExamSupp = new javax.swing.JLabel();
        comboExamSup = new javax.swing.JComboBox<>();
        lExamComp = new javax.swing.JLabel();
        comboExamComp = new javax.swing.JComboBox<>();
        lLunette = new javax.swing.JLabel();
        lGauche1 = new javax.swing.JLabel();
        lDroit1 = new javax.swing.JLabel();
        lLunetteA = new javax.swing.JLabel();
        lLunetteAdd = new javax.swing.JLabel();
        lLunetteS = new javax.swing.JLabel();
        lLunetteC = new javax.swing.JLabel();
        lAC = new javax.swing.JLabel();
        lCyc = new javax.swing.JLabel();
        lSC = new javax.swing.JLabel();
        lAC2 = new javax.swing.JLabel();
        lFondDoeil = new javax.swing.JLabel();
        lLentilleS = new javax.swing.JLabel();
        lLentilleC = new javax.swing.JLabel();
        lLentilleRC = new javax.swing.JLabel();
        lLentilleRC2 = new javax.swing.JLabel();
        lLEntilleD = new javax.swing.JLabel();
        lLentilleA = new javax.swing.JLabel();
        lDentretient = new javax.swing.JLabel();
        lVerre = new javax.swing.JLabel();
        tfPkeG = new javax.swing.JTextField();
        tfPkeD = new javax.swing.JTextField();
        lPKE = new javax.swing.JLabel();
        lLentille = new javax.swing.JLabel();
        lFondVitre = new javax.swing.JLabel();
        lFondMacula = new javax.swing.JLabel();
        lFondCD = new javax.swing.JLabel();
        lFondPapille = new javax.swing.JLabel();
        lFondRetine = new javax.swing.JLabel();
        lgauche3 = new javax.swing.JLabel();
        ldroite3 = new javax.swing.JLabel();
        lgauche4 = new javax.swing.JLabel();
        ldroite4 = new javax.swing.JLabel();
        lLampeAFond = new javax.swing.JLabel();
        lLampePaup = new javax.swing.JLabel();
        lLAmpeCorne = new javax.swing.JLabel();
        lLampeIris = new javax.swing.JLabel();
        lLampeCritalin = new javax.swing.JLabel();
        ltensionocculaire4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfSolG = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfSolD = new javax.swing.JTextArea();
        tfLunetteAddG = new javax.swing.JTextField();
        tfLunetteSG = new javax.swing.JTextField();
        tfLunetteCG = new javax.swing.JTextField();
        tfLunetteAG = new javax.swing.JTextField();
        tfLunetteAddD = new javax.swing.JTextField();
        tfLunetteAD = new javax.swing.JTextField();
        tfLunetteCD = new javax.swing.JTextField();
        tfLunetteSD = new javax.swing.JTextField();
        tfLentilleSG = new javax.swing.JTextField();
        tfLentilleCG = new javax.swing.JTextField();
        tfLentilleAG = new javax.swing.JTextField();
        tfLentilleRCG = new javax.swing.JTextField();
        tfLampeConjG = new javax.swing.JTextField();
        tfLampePaupG = new javax.swing.JTextField();
        tfLampeCornG = new javax.swing.JTextField();
        tfLampeIrisG = new javax.swing.JTextField();
        tfLentilleDG = new javax.swing.JTextField();
        tfLentilleRC2G = new javax.swing.JTextField();
        tfLampeCristG = new javax.swing.JTextField();
        tfLampeConjD = new javax.swing.JTextField();
        tfLampePaupD = new javax.swing.JTextField();
        tfLampeCornD = new javax.swing.JTextField();
        tfLampeIrisD = new javax.swing.JTextField();
        tfLampeCristD = new javax.swing.JTextField();
        tfFondVitreD = new javax.swing.JTextField();
        tfFondMaculaD = new javax.swing.JTextField();
        tfFondCDD = new javax.swing.JTextField();
        tfFondPapilleD = new javax.swing.JTextField();
        tffondRetineD = new javax.swing.JTextField();
        tfFondVitreG = new javax.swing.JTextField();
        tfFondMaculaG = new javax.swing.JTextField();
        tfFondCDG = new javax.swing.JTextField();
        tfFondPapilleG = new javax.swing.JTextField();
        tfFondRetineG = new javax.swing.JTextField();
        tfACG = new javax.swing.JTextField();
        tfCycG = new javax.swing.JTextField();
        tfSCG = new javax.swing.JTextField();
        tfACG2 = new javax.swing.JTextField();
        jTextField39 = new javax.swing.JTextField();
        tfACD = new javax.swing.JTextField();
        tfCycD = new javax.swing.JTextField();
        tfSCD = new javax.swing.JTextField();
        tfACD2 = new javax.swing.JTextField();
        jTextField44 = new javax.swing.JTextField();
        tfVerreG = new javax.swing.JTextField();
        tfVerreD = new javax.swing.JTextField();
        tfLentilleSD = new javax.swing.JTextField();
        tfLentilleCD = new javax.swing.JTextField();
        tfLentilleAD = new javax.swing.JTextField();
        tfLentilleRCD = new javax.swing.JTextField();
        tfLentilleRC2D = new javax.swing.JTextField();
        tfLentilleDD = new javax.swing.JTextField();
        lSolution = new javax.swing.JLabel();
        lLampeConj = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        ltypeconsult1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panQuitterFicheMed.setBackground(new java.awt.Color(204, 204, 204));
        panQuitterFicheMed.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lQuitterFicheMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/show/ihm/x_bleu.png"))); // NOI18N
        lQuitterFicheMed.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lQuitterFicheMedMouseMoved(evt);
            }
        });
        lQuitterFicheMed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lQuitterFicheMedMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lQuitterFicheMedMouseExited(evt);
            }
        });
        panQuitterFicheMed.add(lQuitterFicheMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 20, 20));

        getContentPane().add(panQuitterFicheMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 40, 100));

        panSuperieurFicheMed.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panSuperieurFicheMed.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lReduireFichePerso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/show/ihm/réduire.png"))); // NOI18N
        lReduireFichePerso.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lReduireFichePersoMouseMoved(evt);
            }
        });
        panSuperieurFicheMed.add(lReduireFichePerso, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 20, -1));

        lSuperieurFicheMed.setForeground(new java.awt.Color(0, 0, 51));
        lSuperieurFicheMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/show/ihm/barre_medical.png"))); // NOI18N
        panSuperieurFicheMed.add(lSuperieurFicheMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 70));

        getContentPane().add(panSuperieurFicheMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 930, 70));

        panFicheMed.setBackground(new java.awt.Color(0, 0, 51));
        panFicheMed.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panAnt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 51))); // NOI18N
        panAnt.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lDoc.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lDoc.setForeground(new java.awt.Color(0, 0, 51));
        lDoc.setText("Documents:");
        panAnt.add(lDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, -1, -1));

        tfDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDocActionPerformed(evt);
            }
        });
        panAnt.add(tfDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 130, -1));

        lAntGeneraux.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lAntGeneraux.setForeground(new java.awt.Color(0, 0, 51));
        lAntGeneraux.setText("Antécédents généraux:");
        panAnt.add(lAntGeneraux, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        lAntFamiliaux.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lAntFamiliaux.setForeground(new java.awt.Color(0, 0, 51));
        lAntFamiliaux.setText("Antécédents familiaux:");
        panAnt.add(lAntFamiliaux, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 20));

        lAntOphtalmo.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lAntOphtalmo.setForeground(new java.awt.Color(0, 0, 51));
        lAntOphtalmo.setText("Antécédents ophtalmologiques:");
        panAnt.add(lAntOphtalmo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, -1));

        tfAntFamiliaux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAntFamiliauxActionPerformed(evt);
            }
        });
        panAnt.add(tfAntFamiliaux, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 220, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 51));
        jSeparator2.setDoubleBuffered(true);
        panAnt.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 22, 720, 0));

        tfAntOphtalmo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAntOphtalmoActionPerformed(evt);
            }
        });
        panAnt.add(tfAntOphtalmo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 250, -1));

        lAntecedent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lAntecedent.setForeground(new java.awt.Color(0, 0, 51));
        lAntecedent.setText("ANTECEDENTS :");
        panAnt.add(lAntecedent, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 51));
        jSeparator3.setDoubleBuffered(true);
        panAnt.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 720, 10));

        tfAntGeneraux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAntGenerauxActionPerformed(evt);
            }
        });
        panAnt.add(tfAntGeneraux, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 220, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        panAnt.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 920, 50));

        bimporter.setText("Importer");
        bimporter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bimporterActionPerformed(evt);
            }
        });
        panAnt.add(bimporter, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 70, -1, -1));

        panFicheMed.add(panAnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 930, 110));

        panBoutonFicheMed.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bValiderFicheMed.setText("Valider");
        bValiderFicheMed.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        bValiderFicheMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bValiderFicheMedActionPerformed(evt);
            }
        });
        panBoutonFicheMed.add(bValiderFicheMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 120, 30));

        panFicheMed.add(panBoutonFicheMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, 930, 60));

        panCentreFicheMed.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panCentreFicheMed.setPreferredSize(new java.awt.Dimension(920, 230));
        panCentreFicheMed.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(930, 340));
        jPanel1.setPreferredSize(new java.awt.Dimension(930, 340));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lTypeConsult.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lTypeConsult.setForeground(new java.awt.Color(0, 0, 51));
        lTypeConsult.setText("Type de consultation:");
        jPanel1.add(lTypeConsult, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        comboTypeConsult.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adaptation lentilles", "Contrôle simple", "Contrôle post-opératoire", "Cyclopégie", "Examen de fond d'oeil", "IVT", "Lavage VL", "Laser Argon", "Laser YAG", "Rééducation" }));
        comboTypeConsult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTypeConsultActionPerformed(evt);
            }
        });
        jPanel1.add(comboTypeConsult, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 120, -1));

        lExamSupp.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lExamSupp.setForeground(new java.awt.Color(0, 0, 51));
        lExamSupp.setText("Examens supplémentaires:");
        jPanel1.add(lExamSupp, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, -1));

        comboExamSup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Angiographie", "Autoretraphrométrie", "Echographie A", "Echographie B", "OCT maculaire", "OCT papillaire", "Pachymétrie", "Retinographie", "Test de Schirmer", "Topographie" }));
        jPanel1.add(comboExamSup, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 140, -1));

        lExamComp.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lExamComp.setForeground(new java.awt.Color(0, 0, 51));
        lExamComp.setText("Examens complémentaires:");
        jPanel1.add(lExamComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        comboExamComp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Complications", "Deviomètre", "Etude fixation", "PP", "PPC" }));
        jPanel1.add(comboExamComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 120, -1));

        lLunette.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lLunette.setForeground(new java.awt.Color(0, 0, 51));
        lLunette.setText("Lunettes:");
        jPanel1.add(lLunette, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        lGauche1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lGauche1.setForeground(new java.awt.Color(0, 0, 51));
        lGauche1.setText("  G");
        jPanel1.add(lGauche1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 20, 20));

        lDroit1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lDroit1.setForeground(new java.awt.Color(0, 0, 51));
        lDroit1.setText("  D");
        jPanel1.add(lDroit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 40, 20, 20));

        lLunetteA.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lLunetteA.setForeground(new java.awt.Color(0, 0, 51));
        lLunetteA.setText("  A");
        jPanel1.add(lLunetteA, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 20, 20));

        lLunetteAdd.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lLunetteAdd.setForeground(new java.awt.Color(0, 0, 51));
        lLunetteAdd.setText("Add");
        jPanel1.add(lLunetteAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 30, 20));

        lLunetteS.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lLunetteS.setForeground(new java.awt.Color(0, 0, 51));
        lLunetteS.setText("  S");
        jPanel1.add(lLunetteS, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 20, 20));

        lLunetteC.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lLunetteC.setForeground(new java.awt.Color(0, 0, 51));
        lLunetteC.setText("  C");
        jPanel1.add(lLunetteC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 20, 20));

        lAC.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lAC.setForeground(new java.awt.Color(0, 0, 51));
        lAC.setText("Accuité visuelle (AC):");
        jPanel1.add(lAC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        lCyc.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lCyc.setForeground(new java.awt.Color(0, 0, 51));
        lCyc.setText("Cyclopégie:");
        jPanel1.add(lCyc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        lSC.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lSC.setForeground(new java.awt.Color(0, 0, 51));
        lSC.setText("Accuité visuelle (SC):");
        jPanel1.add(lSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        lAC2.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lAC2.setForeground(new java.awt.Color(0, 0, 51));
        lAC2.setText("Accuité visuelle (AC):");
        jPanel1.add(lAC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        lFondDoeil.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lFondDoeil.setForeground(new java.awt.Color(0, 0, 51));
        lFondDoeil.setText("Fond d'oeil:");
        jPanel1.add(lFondDoeil, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, -1, 40));

        lLentilleS.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lLentilleS.setText("   S");
        jPanel1.add(lLentilleS, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 20, -1));

        lLentilleC.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lLentilleC.setText("   C");
        jPanel1.add(lLentilleC, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 20, -1));

        lLentilleRC.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lLentilleRC.setText("  RC");
        jPanel1.add(lLentilleRC, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 30, -1));

        lLentilleRC2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lLentilleRC2.setText("  RC'");
        jPanel1.add(lLentilleRC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 30, -1));

        lLEntilleD.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lLEntilleD.setText("   D");
        jPanel1.add(lLEntilleD, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 20, -1));

        lLentilleA.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lLentilleA.setText("   A");
        jPanel1.add(lLentilleA, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 20, -1));

        lDentretient.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lDentretient.setForeground(new java.awt.Color(0, 0, 51));
        lDentretient.setText("d'entretient :");
        jPanel1.add(lDentretient, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 80, -1));

        lVerre.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lVerre.setForeground(new java.awt.Color(0, 0, 51));
        lVerre.setText("Verre à 3 mirroirs:");
        jPanel1.add(lVerre, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, -1, -1));
        jPanel1.add(tfPkeG, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 40, -1));
        jPanel1.add(tfPkeD, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, 40, -1));

        lPKE.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lPKE.setForeground(new java.awt.Color(0, 0, 51));
        lPKE.setText("PKE:");
        jPanel1.add(lPKE, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, -1, -1));

        lLentille.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lLentille.setForeground(new java.awt.Color(0, 0, 51));
        lLentille.setText("Lentilles:");
        jPanel1.add(lLentille, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));

        lFondVitre.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lFondVitre.setForeground(new java.awt.Color(0, 0, 51));
        lFondVitre.setText("Vitre");
        jPanel1.add(lFondVitre, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 240, 40, -1));

        lFondMacula.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lFondMacula.setForeground(new java.awt.Color(0, 0, 51));
        lFondMacula.setText(" Macula");
        jPanel1.add(lFondMacula, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 270, 50, -1));

        lFondCD.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lFondCD.setForeground(new java.awt.Color(0, 0, 51));
        lFondCD.setText(" C/D");
        jPanel1.add(lFondCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, 30, -1));

        lFondPapille.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lFondPapille.setForeground(new java.awt.Color(0, 0, 51));
        lFondPapille.setText("  Papille");
        jPanel1.add(lFondPapille, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 330, 50, -1));

        lFondRetine.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lFondRetine.setForeground(new java.awt.Color(0, 0, 51));
        lFondRetine.setText("  Rétine ");
        jPanel1.add(lFondRetine, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 360, 50, -1));

        lgauche3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lgauche3.setText("  G");
        jPanel1.add(lgauche3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, 20, -1));

        ldroite3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        ldroite3.setForeground(new java.awt.Color(0, 0, 51));
        ldroite3.setText("  D");
        jPanel1.add(ldroite3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 40, 20, -1));

        lgauche4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lgauche4.setText("  G");
        jPanel1.add(lgauche4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 20, -1));

        ldroite4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        ldroite4.setText("  D");
        jPanel1.add(ldroite4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 20, -1));

        lLampeAFond.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lLampeAFond.setForeground(new java.awt.Color(0, 0, 51));
        lLampeAFond.setText("Lampe à fond:");
        jPanel1.add(lLampeAFond, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, -1, -1));

        lLampePaup.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lLampePaup.setForeground(new java.awt.Color(0, 0, 51));
        lLampePaup.setText("   Paupière");
        jPanel1.add(lLampePaup, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 90, 70, -1));

        lLAmpeCorne.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lLAmpeCorne.setForeground(new java.awt.Color(0, 0, 51));
        lLAmpeCorne.setText(" Cornée");
        jPanel1.add(lLAmpeCorne, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 120, 50, -1));

        lLampeIris.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lLampeIris.setForeground(new java.awt.Color(0, 0, 51));
        lLampeIris.setText(" Iris");
        jPanel1.add(lLampeIris, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 150, 30, -1));

        lLampeCritalin.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lLampeCritalin.setForeground(new java.awt.Color(0, 0, 51));
        lLampeCritalin.setText("Cristalin");
        jPanel1.add(lLampeCritalin, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 180, 50, -1));

        ltensionocculaire4.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        ltensionocculaire4.setForeground(new java.awt.Color(0, 0, 51));
        ltensionocculaire4.setText("Tension occulaire:");
        jPanel1.add(ltensionocculaire4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        tfSolG.setColumns(20);
        tfSolG.setRows(5);
        jScrollPane1.setViewportView(tfSolG);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 120, 140));

        tfSolD.setColumns(20);
        tfSolD.setRows(5);
        jScrollPane2.setViewportView(tfSolD);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 120, 140));
        jPanel1.add(tfLunetteAddG, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 40, -1));
        jPanel1.add(tfLunetteSG, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 40, -1));
        jPanel1.add(tfLunetteCG, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 40, -1));
        jPanel1.add(tfLunetteAG, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 40, -1));
        jPanel1.add(tfLunetteAddD, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 40, -1));
        jPanel1.add(tfLunetteAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 40, -1));
        jPanel1.add(tfLunetteCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 40, -1));
        jPanel1.add(tfLunetteSD, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 40, -1));
        jPanel1.add(tfLentilleSG, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 40, -1));
        jPanel1.add(tfLentilleCG, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 40, -1));
        jPanel1.add(tfLentilleAG, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 40, -1));
        jPanel1.add(tfLentilleRCG, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 40, -1));

        tfLampeConjG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLampeConjGActionPerformed(evt);
            }
        });
        jPanel1.add(tfLampeConjG, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, 40, -1));
        jPanel1.add(tfLampePaupG, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, 40, -1));
        jPanel1.add(tfLampeCornG, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, 40, -1));
        jPanel1.add(tfLampeIrisG, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, 40, -1));
        jPanel1.add(tfLentilleDG, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 40, -1));
        jPanel1.add(tfLentilleRC2G, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 40, -1));
        jPanel1.add(tfLampeCristG, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, 40, -1));

        tfLampeConjD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLampeConjDActionPerformed(evt);
            }
        });
        jPanel1.add(tfLampeConjD, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 60, 40, -1));
        jPanel1.add(tfLampePaupD, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 90, 40, -1));
        jPanel1.add(tfLampeCornD, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 120, 40, -1));
        jPanel1.add(tfLampeIrisD, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 150, 40, -1));
        jPanel1.add(tfLampeCristD, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 180, 40, -1));

        tfFondVitreD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFondVitreDActionPerformed(evt);
            }
        });
        jPanel1.add(tfFondVitreD, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 240, 40, -1));
        jPanel1.add(tfFondMaculaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 270, 40, -1));
        jPanel1.add(tfFondCDD, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 300, 40, -1));
        jPanel1.add(tfFondPapilleD, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 330, 40, -1));
        jPanel1.add(tffondRetineD, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 360, 40, -1));

        tfFondVitreG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFondVitreGActionPerformed(evt);
            }
        });
        jPanel1.add(tfFondVitreG, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, 40, -1));
        jPanel1.add(tfFondMaculaG, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 270, 40, -1));
        jPanel1.add(tfFondCDG, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 300, 40, -1));
        jPanel1.add(tfFondPapilleG, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 330, 40, -1));
        jPanel1.add(tfFondRetineG, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 360, 40, -1));

        tfACG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfACGActionPerformed(evt);
            }
        });
        jPanel1.add(tfACG, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 40, -1));
        jPanel1.add(tfCycG, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 40, -1));
        jPanel1.add(tfSCG, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 40, -1));
        jPanel1.add(tfACG2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 40, -1));
        jPanel1.add(jTextField39, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 40, -1));

        tfACD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfACDActionPerformed(evt);
            }
        });
        jPanel1.add(tfACD, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 40, -1));
        jPanel1.add(tfCycD, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 40, -1));
        jPanel1.add(tfSCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 40, -1));
        jPanel1.add(tfACD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 40, -1));
        jPanel1.add(jTextField44, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 40, -1));
        jPanel1.add(tfVerreG, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 390, 40, -1));
        jPanel1.add(tfVerreD, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 390, 40, -1));
        jPanel1.add(tfLentilleSD, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 40, -1));
        jPanel1.add(tfLentilleCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 40, -1));
        jPanel1.add(tfLentilleAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 40, -1));
        jPanel1.add(tfLentilleRCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 40, -1));
        jPanel1.add(tfLentilleRC2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 40, -1));
        jPanel1.add(tfLentilleDD, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 40, -1));

        lSolution.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lSolution.setForeground(new java.awt.Color(0, 0, 51));
        lSolution.setText("Solutions");
        jPanel1.add(lSolution, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

        lLampeConj.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lLampeConj.setForeground(new java.awt.Color(0, 0, 51));
        lLampeConj.setText("Conjonctive");
        jPanel1.add(lLampeConj, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 60, 70, -1));

        panCentreFicheMed.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 890, 410));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 51));
        jSeparator1.setDoubleBuffered(true);
        panCentreFicheMed.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 700, -1));

        ltypeconsult1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ltypeconsult1.setForeground(new java.awt.Color(0, 0, 51));
        ltypeconsult1.setText("CONSULTATION :");
        panCentreFicheMed.add(ltypeconsult1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 2, -1, 20));

        panFicheMed.add(panCentreFicheMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 930, 450));

        getContentPane().add(panFicheMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDocActionPerformed

    private void tfAntFamiliauxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAntFamiliauxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAntFamiliauxActionPerformed

    private void tfAntOphtalmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAntOphtalmoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAntOphtalmoActionPerformed

    private void tfAntGenerauxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAntGenerauxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAntGenerauxActionPerformed

    private void tfACDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfACDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfACDActionPerformed

    private void tfACGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfACGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfACGActionPerformed

    private void tfFondVitreGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFondVitreGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFondVitreGActionPerformed

    private void tfFondVitreDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFondVitreDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFondVitreDActionPerformed

    private void tfLampeConjDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLampeConjDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLampeConjDActionPerformed

    private void tfLampeConjGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLampeConjGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLampeConjGActionPerformed

    private void comboTypeConsultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTypeConsultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTypeConsultActionPerformed

    private void bValiderFicheMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bValiderFicheMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bValiderFicheMedActionPerformed

    private void lQuitterFicheMedMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lQuitterFicheMedMouseMoved
        setCursor(HAND_CURSOR);
    }//GEN-LAST:event_lQuitterFicheMedMouseMoved

    private void lQuitterFicheMedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lQuitterFicheMedMouseExited
        setCursor(DEFAULT_CURSOR);
    }//GEN-LAST:event_lQuitterFicheMedMouseExited

    private void lQuitterFicheMedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lQuitterFicheMedMouseClicked
        int quitter = JOptionPane.showConfirmDialog(this, "Voulez vous vraiment quitter !", "Confirmation ", JOptionPane.YES_NO_OPTION);
        if (quitter == 0) {
            this.setVisible(false);

        }
    }//GEN-LAST:event_lQuitterFicheMedMouseClicked

    private void bimporterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bimporterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bimporterActionPerformed

    private void lReduireFichePersoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lReduireFichePersoMouseMoved
        setCursor(HAND_CURSOR);
    }//GEN-LAST:event_lReduireFichePersoMouseMoved

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed

    }//GEN-LAST:event_formMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fiche_Medicale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fiche_Medicale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fiche_Medicale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fiche_Medicale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fiche_Medicale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bValiderFicheMed;
    private javax.swing.JButton bimporter;
    private javax.swing.JComboBox<String> comboExamComp;
    private javax.swing.JComboBox<String> comboExamSup;
    private javax.swing.JComboBox<String> comboTypeConsult;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField44;
    private javax.swing.JLabel lAC;
    private javax.swing.JLabel lAC2;
    private javax.swing.JLabel lAntFamiliaux;
    private javax.swing.JLabel lAntGeneraux;
    private javax.swing.JLabel lAntOphtalmo;
    private javax.swing.JLabel lAntecedent;
    private javax.swing.JLabel lCyc;
    private javax.swing.JLabel lDentretient;
    private javax.swing.JLabel lDoc;
    private javax.swing.JLabel lDroit1;
    private javax.swing.JLabel lExamComp;
    private javax.swing.JLabel lExamSupp;
    private javax.swing.JLabel lFondCD;
    private javax.swing.JLabel lFondDoeil;
    private javax.swing.JLabel lFondMacula;
    private javax.swing.JLabel lFondPapille;
    private javax.swing.JLabel lFondRetine;
    private javax.swing.JLabel lFondVitre;
    private javax.swing.JLabel lGauche1;
    private javax.swing.JLabel lLAmpeCorne;
    private javax.swing.JLabel lLEntilleD;
    private javax.swing.JLabel lLampeAFond;
    private javax.swing.JLabel lLampeConj;
    private javax.swing.JLabel lLampeCritalin;
    private javax.swing.JLabel lLampeIris;
    private javax.swing.JLabel lLampePaup;
    private javax.swing.JLabel lLentille;
    private javax.swing.JLabel lLentilleA;
    private javax.swing.JLabel lLentilleC;
    private javax.swing.JLabel lLentilleRC;
    private javax.swing.JLabel lLentilleRC2;
    private javax.swing.JLabel lLentilleS;
    private javax.swing.JLabel lLunette;
    private javax.swing.JLabel lLunetteA;
    private javax.swing.JLabel lLunetteAdd;
    private javax.swing.JLabel lLunetteC;
    private javax.swing.JLabel lLunetteS;
    private javax.swing.JLabel lPKE;
    private javax.swing.JLabel lQuitterFicheMed;
    private javax.swing.JLabel lReduireFichePerso;
    private javax.swing.JLabel lSC;
    private javax.swing.JLabel lSolution;
    private javax.swing.JLabel lSuperieurFicheMed;
    private javax.swing.JLabel lTypeConsult;
    private javax.swing.JLabel lVerre;
    private javax.swing.JLabel ldroite3;
    private javax.swing.JLabel ldroite4;
    private javax.swing.JLabel lgauche3;
    private javax.swing.JLabel lgauche4;
    private javax.swing.JLabel ltensionocculaire4;
    private javax.swing.JLabel ltypeconsult1;
    private javax.swing.JPanel panAnt;
    private javax.swing.JPanel panBoutonFicheMed;
    private javax.swing.JPanel panCentreFicheMed;
    private javax.swing.JPanel panFicheMed;
    private javax.swing.JPanel panQuitterFicheMed;
    private javax.swing.JPanel panSuperieurFicheMed;
    private javax.swing.JTextField tfACD;
    private javax.swing.JTextField tfACD2;
    private javax.swing.JTextField tfACG;
    private javax.swing.JTextField tfACG2;
    private javax.swing.JTextField tfAntFamiliaux;
    private javax.swing.JTextField tfAntGeneraux;
    private javax.swing.JTextField tfAntOphtalmo;
    private javax.swing.JTextField tfCycD;
    private javax.swing.JTextField tfCycG;
    private javax.swing.JTextField tfDoc;
    private javax.swing.JTextField tfFondCDD;
    private javax.swing.JTextField tfFondCDG;
    private javax.swing.JTextField tfFondMaculaD;
    private javax.swing.JTextField tfFondMaculaG;
    private javax.swing.JTextField tfFondPapilleD;
    private javax.swing.JTextField tfFondPapilleG;
    private javax.swing.JTextField tfFondRetineG;
    private javax.swing.JTextField tfFondVitreD;
    private javax.swing.JTextField tfFondVitreG;
    private javax.swing.JTextField tfLampeConjD;
    private javax.swing.JTextField tfLampeConjG;
    private javax.swing.JTextField tfLampeCornD;
    private javax.swing.JTextField tfLampeCornG;
    private javax.swing.JTextField tfLampeCristD;
    private javax.swing.JTextField tfLampeCristG;
    private javax.swing.JTextField tfLampeIrisD;
    private javax.swing.JTextField tfLampeIrisG;
    private javax.swing.JTextField tfLampePaupD;
    private javax.swing.JTextField tfLampePaupG;
    private javax.swing.JTextField tfLentilleAD;
    private javax.swing.JTextField tfLentilleAG;
    private javax.swing.JTextField tfLentilleCD;
    private javax.swing.JTextField tfLentilleCG;
    private javax.swing.JTextField tfLentilleDD;
    private javax.swing.JTextField tfLentilleDG;
    private javax.swing.JTextField tfLentilleRC2D;
    private javax.swing.JTextField tfLentilleRC2G;
    private javax.swing.JTextField tfLentilleRCD;
    private javax.swing.JTextField tfLentilleRCG;
    private javax.swing.JTextField tfLentilleSD;
    private javax.swing.JTextField tfLentilleSG;
    private javax.swing.JTextField tfLunetteAD;
    private javax.swing.JTextField tfLunetteAG;
    private javax.swing.JTextField tfLunetteAddD;
    private javax.swing.JTextField tfLunetteAddG;
    private javax.swing.JTextField tfLunetteCD;
    private javax.swing.JTextField tfLunetteCG;
    private javax.swing.JTextField tfLunetteSD;
    private javax.swing.JTextField tfLunetteSG;
    private javax.swing.JTextField tfPkeD;
    private javax.swing.JTextField tfPkeG;
    private javax.swing.JTextField tfSCD;
    private javax.swing.JTextField tfSCG;
    private javax.swing.JTextArea tfSolD;
    private javax.swing.JTextArea tfSolG;
    private javax.swing.JTextField tfVerreD;
    private javax.swing.JTextField tfVerreG;
    private javax.swing.JTextField tffondRetineD;
    // End of variables declaration//GEN-END:variables
}
