/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;

/**
 *
 * @author PC MC
 */
public class Reglement extends javax.swing.JFrame {

int X,Y;
    public Reglement() {
        initComponents();
        addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                //To change body of generated methods, choose Tools | Templates.
                X = e.getX();
                Y = e.getY();
            }

        });
        addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseDragged(MouseEvent e) {
                //To change body of generated methods, choose Tools | Templates.
                int depX = e.getX() - X;
                int depY = e.getY() - Y;
                setLocation(getX()+depX,getY()+depY);

            }

        });
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panReglement = new javax.swing.JPanel();
        panQuitterReglement = new javax.swing.JPanel();
        lQuitterReglement = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bFacturer = new javax.swing.JButton();
        tfTarif = new javax.swing.JTextField();
        ltarif2 = new javax.swing.JLabel();
        panSuperieurReglement = new javax.swing.JPanel();
        ltarif = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panReglement.setBackground(new java.awt.Color(0, 0, 51));
        panReglement.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panQuitterReglement.setBackground(new java.awt.Color(204, 204, 204));
        panQuitterReglement.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lQuitterReglement.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lQuitterReglement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/show/ihm/x_bleu.png"))); // NOI18N
        lQuitterReglement.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lQuitterReglementMouseMoved(evt);
            }
        });
        lQuitterReglement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lQuitterReglementMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lQuitterReglementMouseExited(evt);
            }
        });
        panQuitterReglement.add(lQuitterReglement, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        panReglement.add(panQuitterReglement, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 40, 90));

        jPanel1.setMinimumSize(new java.awt.Dimension(1008, 6400));
        jPanel1.setPreferredSize(new java.awt.Dimension(1008, 640));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bFacturer.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bFacturer.setText("Facturer");
        bFacturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFacturerActionPerformed(evt);
            }
        });
        jPanel1.add(bFacturer, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));
        jPanel1.add(tfTarif, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 190, -1));

        ltarif2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ltarif2.setForeground(new java.awt.Color(0, 0, 51));
        ltarif2.setText("Tarif:");
        jPanel1.add(ltarif2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        panReglement.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 380, 140));

        panSuperieurReglement.setBackground(new java.awt.Color(255, 255, 255));
        panSuperieurReglement.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ltarif.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ltarif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/show/ihm/BarreReglement.final.png"))); // NOI18N
        panSuperieurReglement.add(ltarif, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 130, -1));

        panReglement.add(panSuperieurReglement, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 60));

        getContentPane().add(panReglement, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bFacturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFacturerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bFacturerActionPerformed

    private void lQuitterReglementMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lQuitterReglementMouseMoved
        setCursor(HAND_CURSOR);
    }//GEN-LAST:event_lQuitterReglementMouseMoved

    private void lQuitterReglementMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lQuitterReglementMouseExited
       setCursor(DEFAULT_CURSOR);
    }//GEN-LAST:event_lQuitterReglementMouseExited

    private void lQuitterReglementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lQuitterReglementMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_lQuitterReglementMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reglement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reglement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reglement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reglement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reglement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bFacturer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lQuitterReglement;
    private javax.swing.JLabel ltarif;
    private javax.swing.JLabel ltarif2;
    private javax.swing.JPanel panQuitterReglement;
    private javax.swing.JPanel panReglement;
    private javax.swing.JPanel panSuperieurReglement;
    private javax.swing.JTextField tfTarif;
    // End of variables declaration//GEN-END:variables
}
